name: "Continuous Integration Workflow"

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  IAC-Scan:
    runs-on: ubuntu-latest
    name: 
      Infrastructure as Code Scan

      # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout repo
        uses: actions/checkout@v2

      # Run Prisma IaC Scan
      - name: Run Bridgecrew
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        env:
          PRISMA_API_URL: https://api2.eu.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          soft_fail: true
          download_external_modules: true